### ISSUE TITLE
Location of related posts are lost and unseen

### ISSUE THREAD

**Issue by katandmouse** [keesiemeijer/related-posts-by-taxonomy#1]
I love this plugin but am unhappy that appears so far down on the page. Check this out, for example, http://vanillaqueen.com/whats-the-best-vanilla-extract/ Most people leave at the bottom of the post. That's where I'd like the related posts to be. Is there a way to put them either under the sharing icons or under the author box instead of under all the comments where they are not seen?

**Comment by keesiemeijer** [comment]
Are you adding them like this?
https://keesiemeijer.wordpress.com/related-posts-by-taxonomy/#after-content

**Comment by keesiemeijer** [comment]
Please post your question in the WordPress forum for this plugin
https://wordpress.org/support/plugin/related-posts-by-taxonomy
