### ISSUE TITLE
Minimum number of related posts

### ISSUE THREAD

**Issue by clem109** [keesiemeijer/related-posts-by-taxonomy#2]
I'm trying to lower the number of related posts to be displayed below the default of 5, unfortunately it doesn't seem to be working.

Any suggestions? 

Thanks

**Comment by keesiemeijer** [comment]
What have you tried?

For the shortcode you can use the posts_per_page attribute
https://keesiemeijer.wordpress.com/related-posts-by-taxonomy/#posts-per-page

**Comment by clem109** [comment]
So I found the issue, basically its to do with text formatting when you write a post. If when you add the short code and the text is formatted in a certain way it doesn't work. It would be perhaps worth mentioning for other people who come across the same issue.

**Comment by keesiemeijer** [comment]
Arg, sorry for the late reply. Can you tell me what kind of formatting?
